### ISSUE TITLE
Problem with markdown

### ISSUE THREAD

**Issue by Jovi-x** [starkfell/100DaysOfIaC#1]
Hi,
Maybe I'm doing something wrong. I have instaled VS Code, also added extensions:
Markdown All in One
Markdown Lint
Spell Right
I don't know what next. I download pdf & I can't open in VS Code. Please help me.

**Comment by starkfell** [comment]
Jovi,

The PDF document is only for reference purposes on what's possible when using Markdown.

If you are trying to test out using Markdown, go ahead and create a new document in VS Code called **sandbox.md**. The **md** extension on the end is important so VS Code will automatically associate the file as being in markdown format.

Once you have the file opened in place, you can copy and paste the content of the Markdown Cheatsheet in the document from the raw format available in GitHub for any document:

https://raw.githubusercontent.com/starkfell/100DaysOfIaC/master/resources/Markdown_Cheatsheet.md

From this point, you should be on your way to testing out Markdown. Note that any file in any repository on GitHub with a **md** extension can be viewed in **raw** format to see how the markdown is written,

I hope this helps you out.

**Comment by pzerger** [comment]
@Jovi-x did you get this sorted?
