### ISSUE TITLE
Azure Policy?

### ISSUE THREAD

**Issue by v-irtual** [starkfell/100DaysOfIaC#3]
If appropriate, I think covering the use of Azure Policy would be extremely beneficial, especially for enterprises.

**Comment by pzerger** [comment]
We agree. Fortunately, 82 opportunities remain to grant your wish!

**Comment by pzerger** [comment]
Done! Have a look at Day 48, but assume more posts on policy will follow in the next 52 installments that remain. https://github.com/starkfell/100DaysOfIaC/blob/master/articles/day.48.int.azure.policy.eval.in.pipelines.md
